Milestone three review
rOluochKe/redux-bookstore pull request #4
Opened 2020-08-28 15:07 UTC by rOluochKe

### In this milestone, I added the following:-
- adding a book item
- removing a book item

2020-08-28 18:14 UTC, suretrust requested changes
Hi team, 👋 

### Great job thus far! 🙌 Please see my comments. 👇 

**KIndly submit another CRR once these issues have been solved.** _Happy coding!_ 🎉

2020-08-28 18:14 UTC, suretrust commented on src/containers/BooksForm.js
> +    }
You can set this automatically using `name`.
```suggestion
  const name = event.target.name;

  this.setState({
    title: event.target.value
    [name]: event.target.value
  })

```

2020-08-28 18:14 UTC, suretrust commented on src/components/Book.js
> +        </button>
This should be implemented in `BookList` component.
```suggestion
        <button className="btn3" type="submit" onClick={removeBook}>
          Remove Book
        </button>
```

2020-08-28 18:14 UTC, suretrust commented on src/containers/BooksList.js
> +const BooksList = ({ state, removeBook }) => (
* [ ] it implements `handleBookRemove` [screenshot from pathwright](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/bookstore/milestone3/ImplementsRemoveBook.png)
- [ ] Instead of `state`, we could use a more descriptive name, like book. `state` is general in `React`, hence, it's going to be confusing.

```suggestion
const BooksList = ({ book, removeBook }) => {(
const handleRemoveBook = () => removeBook(book)
```

2020-08-28 18:14 UTC, suretrust commented on src/containers/BooksList.js
> +      {state.map(book => <Book key={Math.random() * 1000} book={book} removeBook={removeBook} />)}
* [ ] it passes `handleRemoveBook` to Book component [screenshot from pathwright](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/bookstore/milestone3/ImplementsRemoveBook.png)
```suggestion
      {state.map(book => <Book key={Math.random() * 1000} book={book} removeBook={handleRemoveBook} />)}
```

2020-08-29 00:34 UTC, Forison commented on src/containers/BooksForm.js
> +      id: Math.ceil(Math.random() * 1000),
#### This line of code will not guarantee a generation of unique ids, it will rather create a random number. 
#### what is it create the same number twice along the line?🤔
#### There are packages available to ensure unique number creation. Try ```short-id```🤗.

2020-08-29 00:34 UTC, Forison commented on src/containers/BooksList.js
> +      {book.map(book => <Book key={Math.random() * 1000} book={book} handleRemoveBook={handleRemoveBook} />)}
#### This line of code will not guarantee a generation of unique ids, it will rather create a random number. 
#### what is it create the same number twice along the line?🤔
#### There are packages available to ensure unique number creation. Try ```short-id```🤗.

2020-08-29 09:53 UTC, merged